kafka:
  clusters:
    - name: spotoncars
      bootstrapServers: "${KAFKA_BROKER}"
      properties:
        sasl.mechanism: SCRAM-SHA-512
        security.protocol: SASL_SSL
        sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";
      schemaRegistry: UPSTASH_KAFKA_REST_URL/schema-registry
      schemaRegistryAuth:
        username: "${KAFKA_USERNAME}"
        password: "${KAFKA_PASSWORD}"
